#!/usr/bin/env npx tsx
/**
 * ADW Plan & Build - AI Developer Workflow
 *
 * Usage: npx tsx adws/adwPlanBuild.tsx <github-issue-number> [adw-id]
 *
 * Workflow:
 * 1. Fetch GitHub issue details
 * 2. Create feature branch: feature/issue-{number}-{slug}
 * 3. Plan Agent: Generate implementation plan
 * 4. Build Agent: Implement the solution
 * 5. Create PR with full context
 *
 * Environment Requirements:
 * - ANTHROPIC_API_KEY: Anthropic API key
 * - CLAUDE_CODE_PATH: Path to Claude CLI (default: /usr/local/bin/claude)
 * - GITHUB_PAT: (Optional) GitHub Personal Access Token
 */

import * as path from 'path';
import { log, generateAdwId, ensureLogsDirectory } from './utils';
import { fetchGitHubIssue, commentOnIssue } from './githubApi';
import { createFeatureBranch, commitChanges } from './gitOperations';
import { runPlanAgent, getPlanFilePath } from './planAgent';
import { runBuildAgent } from './buildAgent';
import { createPullRequest } from './pullRequestCreator';
import { runClaudeAgent } from './claudeAgent';
import { GitHubIssue, IssueClassSlashCommand } from './dataTypes';

/**
 * Classifies a GitHub issue as feature, bug, or chore using the haiku model.
 */
async function classifyIssue(issue: GitHubIssue, logsDir: string): Promise<IssueClassSlashCommand> {
  const labelsText = issue.labels.map(l => l.name).join(', ') || 'none';

  const prompt = `Based on the Github Issue below, follow the Instructions to select the appropriate command to execute based on the Command Mapping.

## Instructions

- Based on the details in the Github Issue, select the appropriate command to execute.
- Respond exclusively with '/' followed by the command to execute.
- Use the command mapping to help you decide which command to respond with.
- Think hard about the command to execute.

## Command Mapping

- Respond with /chore if the issue is a chore.
- Respond with /bug if the issue is a bug.
- Respond with /feature if the issue is a feature.
- Respond with 0 if the issue isn't any of the above.

## Github Issue

**Title:** ${issue.title}
**Labels:** ${labelsText}

${issue.body || 'No description provided.'}`;

  const outputFile = path.join(logsDir, 'classifier-agent.jsonl');
  const result = await runClaudeAgent(prompt, 'Classifier', outputFile, 'haiku');

  if (!result.success) {
    log('Classification failed, defaulting to /feature', 'info');
    return '/feature';
  }

  const output = result.output.trim();
  const validCommands: IssueClassSlashCommand[] = ['/feature', '/bug', '/chore'];

  for (const cmd of validCommands) {
    if (output.includes(cmd)) {
      return cmd;
    }
  }

  if (output === '0') {
    log('Issue classified as unknown type, defaulting to /feature', 'info');
    return '/feature';
  }

  log('Could not parse classification result, defaulting to /feature', 'info');
  return '/feature';
}

const commitPrefixMap: Record<IssueClassSlashCommand, string> = {
  '/feature': 'feat:',
  '/bug': 'fix:',
  '/chore': 'chore:',
};

/**
 * Formats a plan completion comment for the GitHub issue.
 */
function formatPlanComment(
  issueNumber: number,
  branchName: string,
  adwId: string,
  planOutput: string
): string {
  const truncatedOutput = planOutput.length > 2000
    ? planOutput.substring(0, 2000) + '...'
    : planOutput;

  return `## Implementation Plan Created

An implementation plan has been generated for this issue.

**Plan file:** \`${getPlanFilePath(issueNumber)}\`
**Branch:** \`${branchName}\`
**ADW ID:** \`${adwId}\`

<details>
<summary>Plan Summary</summary>

${truncatedOutput}

</details>

Generated by ADW Plan Agent`;
}

/**
 * Formats a build completion comment for the GitHub issue.
 */
function formatBuildComment(
  branchName: string,
  adwId: string,
  buildOutput: string
): string {
  const truncatedOutput = buildOutput.length > 2000
    ? buildOutput.substring(0, 2000) + '...'
    : buildOutput;

  return `## Implementation Complete

The implementation for this issue has been completed.

**Branch:** \`${branchName}\`
**ADW ID:** \`${adwId}\`

<details>
<summary>Implementation Summary</summary>

${truncatedOutput}

</details>

Generated by ADW Build Agent`;
}

/**
 * Prints the final workflow summary.
 */
function printWorkflowSummary(
  issueNumber: number,
  issueTitle: string,
  branchName: string,
  logsDir: string,
  prUrl: string,
  planCostUsd: number,
  buildCostUsd: number
): void {
  log('===================================', 'info');
  log('ADW Plan & Build workflow completed!', 'success');
  log(`Issue: #${issueNumber} - ${issueTitle}`, 'info');
  log(`Branch: ${branchName}`, 'info');
  log(`Plan: ${getPlanFilePath(issueNumber)}`, 'info');

  if (prUrl) {
    log(`PR: ${prUrl}`, 'info');
  }

  log(`Logs: ${logsDir}`, 'info');

  const totalCost = planCostUsd + buildCostUsd;
  if (totalCost > 0) {
    log(`Total cost: $${totalCost.toFixed(4)}`, 'info');
  }

  log('===================================', 'info');
}

/**
 * Prints usage information and exits.
 */
function printUsageAndExit(): never {
  console.error('Usage: npx tsx adws/adwPlanBuild.tsx <github-issue-number> [adw-id]');
  console.error('');
  console.error('Environment Requirements:');
  console.error('  ANTHROPIC_API_KEY  - Anthropic API key');
  console.error('  CLAUDE_CODE_PATH   - Path to Claude CLI (default: /usr/local/bin/claude)');
  console.error('  GITHUB_PAT         - (Optional) GitHub Personal Access Token');
  process.exit(1);
}

/**
 * Parses and validates command line arguments.
 */
function parseArguments(args: string[]): { issueNumber: number; adwId: string } {
  if (args.length < 1) {
    printUsageAndExit();
  }

  const issueNumber = parseInt(args[0], 10);
  if (isNaN(issueNumber)) {
    console.error(`Invalid issue number: ${args[0]}`);
    process.exit(1);
  }

  const adwId = args[1] || generateAdwId();

  return { issueNumber, adwId };
}

/**
 * Main workflow orchestrator.
 */
async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const { issueNumber, adwId } = parseArguments(args);
  const logsDir = ensureLogsDirectory(adwId);

  log(`Starting ADW Plan & Build workflow`, 'info');
  log(`Issue: #${issueNumber}`, 'info');
  log(`ADW ID: ${adwId}`, 'info');
  log(`Logs: ${logsDir}`, 'info');

  try {
    // Step 1: Fetch GitHub issue
    log('Fetching GitHub issue...', 'info');
    const issue = await fetchGitHubIssue(issueNumber);
    log(`Fetched issue: ${issue.title}`, 'success');

    // Step 1.5: Classify issue type
    log('Classifying issue type...', 'info');
    const issueType = await classifyIssue(issue, logsDir);
    log(`Issue classified as: ${issueType}`, 'success');

    // Step 2: Create feature branch
    log('Creating feature branch...', 'info');
    const branchName = createFeatureBranch(issueNumber, issue.title);
    log(`On branch: ${branchName}`, 'success');

    // Step 3: Run Plan Agent
    log('Running Plan Agent...', 'info');
    const planResult = await runPlanAgent(issue, logsDir, issueType);

    if (!planResult.success) {
      throw new Error(`Plan Agent failed: ${planResult.output}`);
    }

    // Commit plan
    const planCommitted = commitChanges(`${commitPrefixMap[issueType]} add implementation plan for #${issueNumber}`);

    if (planCommitted) {
      const planComment = formatPlanComment(issueNumber, branchName, adwId, planResult.output);
      commentOnIssue(issueNumber, planComment);
    }

    // Step 4: Run Build Agent
    log('Running Build Agent...', 'info');
    const buildResult = await runBuildAgent(issue, logsDir);

    if (!buildResult.success) {
      throw new Error(`Build Agent failed: ${buildResult.output}`);
    }

    // Commit implementation
    const buildCommitted = commitChanges(`feat: implement #${issueNumber} - ${issue.title}`);

    if (buildCommitted) {
      const buildComment = formatBuildComment(branchName, adwId, buildResult.output);
      commentOnIssue(issueNumber, buildComment);
    }

    // Step 5: Create PR
    log('Creating Pull Request...', 'info');
    const prUrl = createPullRequest(issue, planResult.output, buildResult.output);

    // Final summary
    printWorkflowSummary(
      issueNumber,
      issue.title,
      branchName,
      logsDir,
      prUrl,
      planResult.totalCostUsd || 0,
      buildResult.totalCostUsd || 0
    );

  } catch (error) {
    log(`Workflow failed: ${error}`, 'error');
    process.exit(1);
  }
}

main();
