/**
 * Workflow comment formatting and posting functions.
 * Centralizes all GitHub issue comment templates for ADW workflow stages.
 */

import { WorkflowStage, IssueClassSlashCommand } from './dataTypes';
import { commentOnIssue } from './githubApi';
import { log } from './utils';

/**
 * Context information for workflow comments.
 */
export interface WorkflowContext {
  issueNumber: number;
  adwId: string;
  branchName?: string;
  issueType?: IssueClassSlashCommand;
  planPath?: string;
  planOutput?: string;
  buildOutput?: string;
  prUrl?: string;
  errorMessage?: string;
}

/**
 * Maps issue types to human-readable labels.
 */
const issueTypeLabels: Record<IssueClassSlashCommand, string> = {
  '/feature': 'feature',
  '/bug': 'bug',
  '/chore': 'chore',
};

/**
 * Truncates text to a maximum length with ellipsis.
 */
function truncateText(text: string, maxLength: number): string {
  return text.length > maxLength ? text.substring(0, maxLength) + '...' : text;
}

/**
 * Formats the starting workflow comment.
 */
function formatStartingComment(ctx: WorkflowContext): string {
  return `## :rocket: ADW Workflow Started

Starting automated development workflow for this issue.

**ADW ID:** \`${ctx.adwId}\`

_Processing issue..._`;
}

/**
 * Formats the classified comment.
 */
function formatClassifiedComment(ctx: WorkflowContext): string {
  const typeLabel = ctx.issueType ? issueTypeLabels[ctx.issueType] : 'unknown';
  return `## :mag: Issue Classified

Issue classified as: **${typeLabel}**

**ADW ID:** \`${ctx.adwId}\``;
}

/**
 * Formats the branch created comment.
 */
function formatBranchCreatedComment(ctx: WorkflowContext): string {
  return `## :seedling: Branch Created

Working on branch: \`${ctx.branchName}\`

**ADW ID:** \`${ctx.adwId}\``;
}

/**
 * Formats the plan building comment.
 */
function formatPlanBuildingComment(ctx: WorkflowContext): string {
  return `## :pencil: Building Implementation Plan

Generating implementation plan...

**ADW ID:** \`${ctx.adwId}\``;
}

/**
 * Formats the plan created comment.
 */
function formatPlanCreatedComment(ctx: WorkflowContext): string {
  const truncatedOutput = ctx.planOutput ? truncateText(ctx.planOutput, 2000) : '';

  return `## :white_check_mark: Implementation Plan Created

An implementation plan has been generated for this issue.

**Plan file:** \`${ctx.planPath}\`
**Branch:** \`${ctx.branchName}\`
**ADW ID:** \`${ctx.adwId}\`

<details>
<summary>Plan Summary</summary>

${truncatedOutput}

</details>

Generated by ADW Plan Agent`;
}

/**
 * Formats the plan file created comment.
 */
function formatPlanFileCreatedComment(ctx: WorkflowContext): string {
  return `## :page_facing_up: Plan File Created

Plan file confirmed at: \`${ctx.planPath}\`

**ADW ID:** \`${ctx.adwId}\``;
}

/**
 * Formats the plan committing comment.
 */
function formatPlanCommittingComment(ctx: WorkflowContext): string {
  return `## :floppy_disk: Committing Plan

Committing implementation plan to branch...

**ADW ID:** \`${ctx.adwId}\``;
}

/**
 * Formats the implementing comment.
 */
function formatImplementingComment(ctx: WorkflowContext): string {
  return `## :hammer_and_wrench: Implementing Solution

Running Build Agent to implement the solution...

**ADW ID:** \`${ctx.adwId}\``;
}

/**
 * Formats the implemented comment.
 */
function formatImplementedComment(ctx: WorkflowContext): string {
  const truncatedOutput = ctx.buildOutput ? truncateText(ctx.buildOutput, 2000) : '';

  return `## :white_check_mark: Implementation Complete

The implementation for this issue has been completed.

**Branch:** \`${ctx.branchName}\`
**ADW ID:** \`${ctx.adwId}\`

<details>
<summary>Implementation Summary</summary>

${truncatedOutput}

</details>

Generated by ADW Build Agent`;
}

/**
 * Formats the implementation committing comment.
 */
function formatImplementationCommittingComment(ctx: WorkflowContext): string {
  return `## :floppy_disk: Committing Implementation

Committing implementation changes to branch...

**ADW ID:** \`${ctx.adwId}\``;
}

/**
 * Formats the PR creating comment.
 */
function formatPrCreatingComment(ctx: WorkflowContext): string {
  return `## :memo: Creating Pull Request

Creating pull request for review...

**ADW ID:** \`${ctx.adwId}\``;
}

/**
 * Formats the PR created comment.
 */
function formatPrCreatedComment(ctx: WorkflowContext): string {
  return `## :link: Pull Request Created

A pull request has been created for this issue.

**PR:** ${ctx.prUrl}
**ADW ID:** \`${ctx.adwId}\``;
}

/**
 * Formats the completed comment.
 */
function formatCompletedComment(ctx: WorkflowContext): string {
  return `## :tada: ADW Workflow Completed

Automated development workflow completed successfully!

**Branch:** \`${ctx.branchName}\`
**PR:** ${ctx.prUrl}
**ADW ID:** \`${ctx.adwId}\``;
}

/**
 * Formats the error comment.
 */
function formatErrorComment(ctx: WorkflowContext): string {
  return `## :x: ADW Workflow Error

An error occurred during the automated development workflow.

**Error:** ${ctx.errorMessage || 'Unknown error'}
**ADW ID:** \`${ctx.adwId}\`

Please check the logs for more details.`;
}

/**
 * Formats a workflow comment for the given stage.
 */
export function formatWorkflowComment(stage: WorkflowStage, ctx: WorkflowContext): string {
  switch (stage) {
    case 'starting':
      return formatStartingComment(ctx);
    case 'classified':
      return formatClassifiedComment(ctx);
    case 'branch_created':
      return formatBranchCreatedComment(ctx);
    case 'plan_building':
      return formatPlanBuildingComment(ctx);
    case 'plan_created':
      return formatPlanCreatedComment(ctx);
    case 'plan_file_created':
      return formatPlanFileCreatedComment(ctx);
    case 'plan_committing':
      return formatPlanCommittingComment(ctx);
    case 'implementing':
      return formatImplementingComment(ctx);
    case 'implemented':
      return formatImplementedComment(ctx);
    case 'implementation_committing':
      return formatImplementationCommittingComment(ctx);
    case 'pr_creating':
      return formatPrCreatingComment(ctx);
    case 'pr_created':
      return formatPrCreatedComment(ctx);
    case 'completed':
      return formatCompletedComment(ctx);
    case 'error':
      return formatErrorComment(ctx);
    default:
      return `## ADW Workflow Update\n\n**Stage:** ${stage}\n**ADW ID:** \`${ctx.adwId}\``;
  }
}

/**
 * Posts a workflow comment to the GitHub issue.
 * Handles errors gracefully to prevent comment failures from breaking the workflow.
 */
export function postWorkflowComment(
  issueNumber: number,
  stage: WorkflowStage,
  ctx: WorkflowContext
): void {
  try {
    const comment = formatWorkflowComment(stage, ctx);
    commentOnIssue(issueNumber, comment);
  } catch (error) {
    log(`Failed to post workflow comment for stage '${stage}': ${error}`, 'error');
  }
}
