/**
 * Pull Request creation for ADW workflows.
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { GitHubIssue, log } from '../core';
import { getRepoInfo } from './githubApi';
import { getCurrentBranch, pushBranch } from './gitOperations';

/**
 * Generates the PR body with implementation details.
 */
function generatePrBody(
  issue: GitHubIssue,
  planSummary: string,
  buildSummary: string
): string {
  return `## Summary
Implements #${issue.number} - ${issue.title}

## Implementation Plan
${planSummary}

## Changes Made
${buildSummary}

## Testing
- [ ] All validation commands from the plan pass
- [ ] No regressions introduced
- [ ] Code follows project conventions

---
Generated by ADW Plan & Build workflow
`;
}

/**
 * Creates a pull request title from the issue.
 */
function generatePrTitle(issue: GitHubIssue): string {
  return `feat: ${issue.title} (#${issue.number})`;
}

/**
 * Creates a pull request for the current branch.
 * @param issue - The GitHub issue to create a PR for.
 * @param planSummary - Summary of the implementation plan.
 * @param buildSummary - Summary of the build changes.
 * @param baseBranch - The base branch for the PR (default: 'develop').
 * @param cwd - Optional working directory for git operations (e.g., worktree path).
 * @returns The PR URL if successful, empty string otherwise.
 */
export function createPullRequest(
  issue: GitHubIssue,
  planSummary: string,
  buildSummary: string,
  baseBranch: string = 'develop',
  cwd?: string
): string {
  const branchName = getCurrentBranch(cwd);
  const prBody = generatePrBody(issue, planSummary, buildSummary);
  const prTitle = generatePrTitle(issue);

  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'adw-pr-'));
  const tempFilePath = path.join(tempDir, 'pr-body.md');

  try {
    fs.writeFileSync(tempFilePath, prBody, 'utf-8');

    pushBranch(branchName, cwd);

    const prUrl = execSync(
      `gh pr create --title "${prTitle.replace(/"/g, '\\"')}" --body-file "${tempFilePath}" --base ${baseBranch}`,
      { encoding: 'utf-8', shell: '/bin/bash', cwd }
    ).trim();

    log(`Created PR: ${prUrl}`, 'success');
    return prUrl;
  } catch (error) {
    log(`Note: ${error}`, 'info');
    return '';
  } finally {
    try {
      fs.unlinkSync(tempFilePath);
      fs.rmdirSync(tempDir);
    } catch {
      // Ignore cleanup errors
    }
  }
}
