/**
 * Issue workflow comment formatting and posting functions.
 */

import { WorkflowStage, IssueClassSlashCommand, log } from '../core';
import { commentOnIssue } from './githubApi';
import { truncateText } from './workflowCommentsBase';

/** Context information for issue workflow comments. */
export interface WorkflowContext {
  issueNumber: number;
  adwId: string;
  branchName?: string;
  issueType?: IssueClassSlashCommand;
  planPath?: string;
  planOutput?: string;
  buildOutput?: string;
  prUrl?: string;
  errorMessage?: string;
  resumeFrom?: WorkflowStage;
  buildProgress?: {
    turnCount: number;
    toolCount: number;
    lastToolName?: string;
    lastText?: string;
  };
}

const issueTypeLabels: Record<IssueClassSlashCommand, string> = {
  '/feature': 'feature',
  '/bug': 'bug',
  '/chore': 'chore',
  '/pr_review': 'pr-review',
};

function formatStartingComment(ctx: WorkflowContext): string {
  return `## :rocket: ADW Workflow Started\n\nStarting automated development workflow for this issue.\n\n**ADW ID:** \`${ctx.adwId}\`\n\n_Processing issue..._`;
}

function formatClassifiedComment(ctx: WorkflowContext): string {
  const typeLabel = ctx.issueType ? issueTypeLabels[ctx.issueType] : 'unknown';
  return `## :mag: Issue Classified\n\nIssue classified as: **${typeLabel}**\n\n**ADW ID:** \`${ctx.adwId}\``;
}

function formatBranchCreatedComment(ctx: WorkflowContext): string {
  return `## :seedling: Branch Created\n\nWorking on branch: \`${ctx.branchName}\`\n\n**ADW ID:** \`${ctx.adwId}\``;
}

function formatPlanBuildingComment(ctx: WorkflowContext): string {
  return `## :pencil: Building Implementation Plan\n\nGenerating implementation plan...\n\n**ADW ID:** \`${ctx.adwId}\``;
}

function formatPlanCreatedComment(ctx: WorkflowContext): string {
  const truncated = ctx.planOutput ? truncateText(ctx.planOutput, 2000) : '';
  return `## :white_check_mark: Implementation Plan Created\n\nAn implementation plan has been generated for this issue.\n\n**Plan file:** \`${ctx.planPath}\`\n**Branch:** \`${ctx.branchName}\`\n**ADW ID:** \`${ctx.adwId}\`\n\n<details>\n<summary>Plan Summary</summary>\n\n${truncated}\n\n</details>\n\nGenerated by ADW Plan Agent`;
}

function formatPlanFileCreatedComment(ctx: WorkflowContext): string {
  return `## :page_facing_up: Plan File Created\n\nPlan file confirmed at: \`${ctx.planPath}\`\n\n**ADW ID:** \`${ctx.adwId}\``;
}

function formatPlanCommittingComment(ctx: WorkflowContext): string {
  return `## :floppy_disk: Committing Plan\n\nCommitting implementation plan to branch...\n\n**ADW ID:** \`${ctx.adwId}\``;
}

function formatImplementingComment(ctx: WorkflowContext): string {
  return `## :hammer_and_wrench: Implementing Solution\n\nRunning Build Agent to implement the solution...\n\n**ADW ID:** \`${ctx.adwId}\``;
}

function formatBuildProgressComment(ctx: WorkflowContext): string {
  const progress = ctx.buildProgress;
  if (!progress) {
    return `## :gear: Build Progress\n\nBuild in progress...\n\n**ADW ID:** \`${ctx.adwId}\``;
  }
  const lastAction = progress.lastToolName ? `Last action: \`${progress.lastToolName}\`` : '';
  const statusText = progress.lastText ? truncateText(progress.lastText, 300) : '';
  return `## :gear: Build Progress\n\n**Turns completed:** ${progress.turnCount}\n**Tool calls made:** ${progress.toolCount}\n${lastAction}\n\n${statusText ? `**Status:**\n${statusText}` : ''}\n\n**ADW ID:** \`${ctx.adwId}\``;
}

function formatImplementedComment(ctx: WorkflowContext): string {
  const truncated = ctx.buildOutput ? truncateText(ctx.buildOutput, 2000) : '';
  return `## :white_check_mark: Implementation Complete\n\nThe implementation for this issue has been completed.\n\n**Branch:** \`${ctx.branchName}\`\n**ADW ID:** \`${ctx.adwId}\`\n\n<details>\n<summary>Implementation Summary</summary>\n\n${truncated}\n\n</details>\n\nGenerated by ADW Build Agent`;
}

function formatImplementationCommittingComment(ctx: WorkflowContext): string {
  return `## :floppy_disk: Committing Implementation\n\nCommitting implementation changes to branch...\n\n**ADW ID:** \`${ctx.adwId}\``;
}

function formatPrCreatingComment(ctx: WorkflowContext): string {
  return `## :memo: Creating Pull Request\n\nCreating pull request for review...\n\n**ADW ID:** \`${ctx.adwId}\``;
}

function formatPrCreatedComment(ctx: WorkflowContext): string {
  return `## :link: Pull Request Created\n\nA pull request has been created for this issue.\n\n**PR:** ${ctx.prUrl}\n**ADW ID:** \`${ctx.adwId}\``;
}

function formatCompletedComment(ctx: WorkflowContext): string {
  return `## :tada: ADW Workflow Completed\n\nAutomated development workflow completed successfully!\n\n**Branch:** \`${ctx.branchName}\`\n**PR:** ${ctx.prUrl}\n**ADW ID:** \`${ctx.adwId}\``;
}

function formatErrorComment(ctx: WorkflowContext): string {
  return `## :x: ADW Workflow Error\n\nAn error occurred during the automated development workflow.\n\n**Error:** ${ctx.errorMessage || 'Unknown error'}\n**ADW ID:** \`${ctx.adwId}\`\n\nPlease check the logs for more details.`;
}

/** Formats the resuming workflow comment. */
export function formatResumingComment(ctx: WorkflowContext, resumeFrom: WorkflowStage): string {
  return `## :arrows_counterclockwise: ADW Workflow Resuming\n\nResuming automated development workflow from previous run.\n\n**Resuming from:** ${resumeFrom}\n**ADW ID:** \`${ctx.adwId}\``;
}

/** Formats a workflow comment for the given stage. */
export function formatWorkflowComment(stage: WorkflowStage, ctx: WorkflowContext): string {
  switch (stage) {
    case 'starting': return formatStartingComment(ctx);
    case 'resuming': return formatResumingComment(ctx, ctx.resumeFrom || 'starting');
    case 'classified': return formatClassifiedComment(ctx);
    case 'branch_created': return formatBranchCreatedComment(ctx);
    case 'plan_building': return formatPlanBuildingComment(ctx);
    case 'plan_created': return formatPlanCreatedComment(ctx);
    case 'plan_file_created': return formatPlanFileCreatedComment(ctx);
    case 'plan_committing': return formatPlanCommittingComment(ctx);
    case 'implementing': return formatImplementingComment(ctx);
    case 'build_progress': return formatBuildProgressComment(ctx);
    case 'implemented': return formatImplementedComment(ctx);
    case 'implementation_committing': return formatImplementationCommittingComment(ctx);
    case 'pr_creating': return formatPrCreatingComment(ctx);
    case 'pr_created': return formatPrCreatedComment(ctx);
    case 'completed': return formatCompletedComment(ctx);
    case 'error': return formatErrorComment(ctx);
    default: return `## ADW Workflow Update\n\n**Stage:** ${stage}\n**ADW ID:** \`${ctx.adwId}\``;
  }
}

/** Posts a workflow comment to the GitHub issue. */
export function postWorkflowComment(issueNumber: number, stage: WorkflowStage, ctx: WorkflowContext): void {
  try {
    const comment = formatWorkflowComment(stage, ctx);
    commentOnIssue(issueNumber, comment);
  } catch (error) {
    log(`Failed to post workflow comment for stage '${stage}': ${error}`, 'error');
  }
}
