/**
 * Issue workflow comment formatting and posting functions.
 */

import { WorkflowStage, IssueClassSlashCommand, log, type CostBreakdown, formatCostBreakdownMarkdown, type TokenUsageSnapshot } from '../core';
import { commentOnIssue } from './githubApi';
import { ADW_SIGNATURE, truncateText } from './workflowCommentsBase';

/** Context information for issue workflow comments. */
export interface WorkflowContext {
  issueNumber: number;
  adwId: string;
  branchName?: string;
  issueType?: IssueClassSlashCommand;
  planPath?: string;
  planOutput?: string;
  buildOutput?: string;
  prUrl?: string;
  errorMessage?: string;
  resumeFrom?: WorkflowStage;
  buildProgress?: {
    turnCount: number;
    toolCount: number;
    lastToolName?: string;
    lastText?: string;
  };
  costBreakdown?: CostBreakdown;
  /** Which continuation attempt this is (1, 2, 3...) for token limit recovery. */
  tokenContinuationNumber?: number;
  /** Token usage snapshot at the time of interruption. */
  tokenUsage?: TokenUsageSnapshot;
}

const issueTypeLabels: Record<IssueClassSlashCommand, string> = {
  '/feature': 'feature',
  '/bug': 'bug',
  '/chore': 'chore',
  '/pr_review': 'pr-review',
};

function formatStartingComment(ctx: WorkflowContext): string {
  return `## :rocket: ADW Workflow Started\n\nStarting automated development workflow for this issue.\n\n**ADW ID:** \`${ctx.adwId}\`\n\n_Processing issue..._${ADW_SIGNATURE}`;
}

function formatClassifiedComment(ctx: WorkflowContext): string {
  const typeLabel = ctx.issueType ? issueTypeLabels[ctx.issueType] : 'unknown';
  return `## :mag: Issue Classified\n\nIssue classified as: **${typeLabel}**\n\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

function formatBranchCreatedComment(ctx: WorkflowContext): string {
  return `## :seedling: Branch Created\n\nWorking on branch: \`${ctx.branchName}\`\n\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

function formatPlanBuildingComment(ctx: WorkflowContext): string {
  return `## :pencil: Building Implementation Plan\n\nGenerating implementation plan...\n\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

function formatPlanCreatedComment(ctx: WorkflowContext): string {
  const truncated = ctx.planOutput ? truncateText(ctx.planOutput, 2000) : '';
  return `## :white_check_mark: Implementation Plan Created\n\nAn implementation plan has been generated for this issue.\n\n**Plan file:** \`${ctx.planPath}\`\n**Branch:** \`${ctx.branchName}\`\n**ADW ID:** \`${ctx.adwId}\`\n\n<details>\n<summary>Plan Summary</summary>\n\n${truncated}\n\n</details>\n\nGenerated by ADW Plan Agent${ADW_SIGNATURE}`;
}

function formatPlanFileCreatedComment(ctx: WorkflowContext): string {
  return `## :page_facing_up: Plan File Created\n\nPlan file confirmed at: \`${ctx.planPath}\`\n\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

function formatPlanCommittingComment(ctx: WorkflowContext): string {
  return `## :floppy_disk: Committing Plan\n\nCommitting implementation plan to branch...\n\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

function formatImplementingComment(ctx: WorkflowContext): string {
  return `## :hammer_and_wrench: Implementing Solution\n\nRunning Build Agent to implement the solution...\n\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

function formatBuildProgressComment(ctx: WorkflowContext): string {
  const progress = ctx.buildProgress;
  if (!progress) {
    return `## :gear: Build Progress\n\nBuild in progress...\n\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
  }
  const lastAction = progress.lastToolName ? `Last action: \`${progress.lastToolName}\`` : '';
  const statusText = progress.lastText ? truncateText(progress.lastText, 300) : '';
  return `## :gear: Build Progress\n\n**Turns completed:** ${progress.turnCount}\n**Tool calls made:** ${progress.toolCount}\n${lastAction}\n\n${statusText ? `**Status:**\n${statusText}` : ''}\n\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

function formatImplementedComment(ctx: WorkflowContext): string {
  const truncated = ctx.buildOutput ? truncateText(ctx.buildOutput, 2000) : '';
  return `## :white_check_mark: Implementation Complete\n\nThe implementation for this issue has been completed.\n\n**Branch:** \`${ctx.branchName}\`\n**ADW ID:** \`${ctx.adwId}\`\n\n<details>\n<summary>Implementation Summary</summary>\n\n${truncated}\n\n</details>\n\nGenerated by ADW Build Agent${ADW_SIGNATURE}`;
}

function formatImplementationCommittingComment(ctx: WorkflowContext): string {
  return `## :floppy_disk: Committing Implementation\n\nCommitting implementation changes to branch...\n\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

function formatPrCreatingComment(ctx: WorkflowContext): string {
  return `## :memo: Creating Pull Request\n\nCreating pull request for review...\n\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

function formatPrCreatedComment(ctx: WorkflowContext): string {
  return `## :link: Pull Request Created\n\nA pull request has been created for this issue.\n\n**PR:** ${ctx.prUrl}\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

function formatCostSection(ctx: WorkflowContext): string {
  if (!ctx.costBreakdown) return '';
  return `\n\n<details>\n<summary>Cost Breakdown</summary>\n\n${formatCostBreakdownMarkdown(ctx.costBreakdown)}\n\n</details>`;
}

function formatCompletedComment(ctx: WorkflowContext): string {
  const costSection = formatCostSection(ctx);
  return `## :tada: ADW Workflow Completed\n\nAutomated development workflow completed successfully!\n\n**Branch:** \`${ctx.branchName}\`\n**PR:** ${ctx.prUrl}\n**ADW ID:** \`${ctx.adwId}\`${costSection}${ADW_SIGNATURE}`;
}

function formatErrorComment(ctx: WorkflowContext): string {
  const costSection = formatCostSection(ctx);
  return `## :x: ADW Workflow Error\n\nAn error occurred during the automated development workflow.\n\n**Error:** ${ctx.errorMessage || 'Unknown error'}\n**ADW ID:** \`${ctx.adwId}\`\n\nPlease check the logs for more details.${costSection}${ADW_SIGNATURE}`;
}

function formatTokenLimitRecoveryComment(ctx: WorkflowContext): string {
  const continuationNumber = ctx.tokenContinuationNumber ?? 1;
  const usage = ctx.tokenUsage;
  const usageDetails = usage
    ? `\n**Tokens used:** ${usage.totalTokens.toLocaleString()} / ${usage.maxTokens.toLocaleString()} (${(usage.thresholdPercent * 100).toFixed(0)}% threshold)`
    : '';
  return `## :warning: Token Limit Recovery\n\nThe build agent approached the token limit and was gracefully terminated. Spawning a continuation agent to resume implementation.\n\n**Continuation:** #${continuationNumber}${usageDetails}\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

/** Formats the resuming workflow comment. */
export function formatResumingComment(ctx: WorkflowContext, resumeFrom: WorkflowStage): string {
  return `## :arrows_counterclockwise: ADW Workflow Resuming\n\nResuming automated development workflow from previous run.\n\n**Resuming from:** ${resumeFrom}\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
}

/** Formats a workflow comment for the given stage. */
export function formatWorkflowComment(stage: WorkflowStage, ctx: WorkflowContext): string {
  switch (stage) {
    case 'starting': return formatStartingComment(ctx);
    case 'resuming': return formatResumingComment(ctx, ctx.resumeFrom || 'starting');
    case 'classified': return formatClassifiedComment(ctx);
    case 'branch_created': return formatBranchCreatedComment(ctx);
    case 'plan_building': return formatPlanBuildingComment(ctx);
    case 'plan_created': return formatPlanCreatedComment(ctx);
    case 'planFile_created': return formatPlanFileCreatedComment(ctx);
    case 'plan_committing': return formatPlanCommittingComment(ctx);
    case 'implementing': return formatImplementingComment(ctx);
    case 'build_progress': return formatBuildProgressComment(ctx);
    case 'implemented': return formatImplementedComment(ctx);
    case 'implementation_committing': return formatImplementationCommittingComment(ctx);
    case 'pr_creating': return formatPrCreatingComment(ctx);
    case 'pr_created': return formatPrCreatedComment(ctx);
    case 'completed': return formatCompletedComment(ctx);
    case 'error': return formatErrorComment(ctx);
    case 'token_limit_recovery': return formatTokenLimitRecoveryComment(ctx);
    default: return `## ADW Workflow Update\n\n**Stage:** ${stage}\n**ADW ID:** \`${ctx.adwId}\`${ADW_SIGNATURE}`;
  }
}

/** Posts a workflow comment to the GitHub issue. */
export function postWorkflowComment(issueNumber: number, stage: WorkflowStage, ctx: WorkflowContext): void {
  try {
    const comment = formatWorkflowComment(stage, ctx);
    commentOnIssue(issueNumber, comment);
  } catch (error) {
    log(`Failed to post workflow comment for stage '${stage}': ${error}`, 'error');
  }
}
